# Generated by Django 5.2.1 on 2025-06-18 15:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0002_alter_staypagecreate_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayAmenitiesListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stay/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])])),
                ('title', models.TextField(blank=True)),
                ('stay_page_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities_listings', to='stay.staypagecreate')),
            ],
        ),
        migrations.CreateModel(
            name='StayAmenitiesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stay_page_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_amenities_title', to='stay.staypagecreate')),
            ],
        ),
        migrations.CreateModel(
            name='StayBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stay/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])])),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stay_page_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_banner', to='stay.staypagecreate')),
            ],
        ),
        migrations.CreateModel(
            name='StayHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stay/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])])),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stay_page_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_highlights', to='stay.staypagecreate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
