# Generated by Django 5.2.1 on 2025-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0004_stayroomslistings_stayroomstitle_stayexplore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staygallery',
            name='link',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staygallery',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
