# Generated by Django 5.2.1 on 2025-06-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0005_staygallery_link_staygallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staygallery',
            name='link',
        ),
        migrations.RemoveField(
            model_name='staygallery',
            name='title',
        ),
    ]
