# Generated by Django 5.2.1 on 2025-06-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0006_remove_staygallery_link_remove_staygallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayhighlights',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stayhighlights',
            name='original_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
