# Generated by Django 5.2.1 on 2025-06-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0007_stayhighlights_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayhighlights',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
