# Generated by Django 5.2.1 on 2025-06-19 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0008_stayhighlights_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stayamenitieslistings',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stayamenitieslistings',
            name='order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
