# Generated by Django 5.2.1 on 2025-06-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0009_alter_stayamenitieslistings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayexplore',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stayexplore',
            name='stay_page_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore', to='stay.staypagecreate'),
        ),
        migrations.AlterField(
            model_name='stayexplore',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staygallery',
            name='stay_page_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='stay.staypagecreate'),
        ),
    ]
