services:
  mysql:
    image: mysql:8.0
    container_name: mysql_greenhillsdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: greenhillsdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - greenhills_network

  backend:
    build: ./backend
    container_name: greenhills_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: backend.settings

    ports:
      - "6240:8000" # External 6700 -> Internal Django port 8000
    volumes:
      - ./backend:/app
      - media_data:/app/media
    depends_on:
      - mysql
    networks:
      - greenhills_network

  frontend:
    build: ./frontend
    container_name: greenhills_frontend
    restart: always
    ports:
      - "6241:80" # External 6701 -> Internal Nginx serving frontend
    networks:
      - greenhills_network
    depends_on:
      - backend # Optional, if frontend waits for backend during SSR/API calls

  cms:
    build: ./cms
    container_name: greenhills_cms
    restart: always
    ports:
      - "6242:80" # External 6702 -> Internal Nginx serving frontend
    networks:
      - greenhills_network
    depends_on:
      - backend

networks:
  greenhills_network:
    driver: bridge

volumes:
  mysql_data:
  media_data:
