# Generated by Django 5.2.1 on 2025-06-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0002_gatheramenitieslistings_gatheramenitiestitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatherHighlightsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gather_page_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gather_highlights_title', to='gather.gatherpagecreate')),
            ],
        ),
    ]
