# Generated by Django 5.2.1 on 2025-06-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_alter_socialmedialinks_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={},
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
