# Generated by Django 5.2.1 on 2025-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='link',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
