# Generated by Django 5.2.1 on 2025-06-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogposts_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='title_detailed_page',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
