# Generated by Django 5.2.1 on 2025-06-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogposts_title_detailed_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
