# Generated by Django 5.2.1 on 2025-06-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogposts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='link',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
