# Generated by Django 5.2.1 on 2025-07-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogposts_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbanner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
