# Generated by Django 5.2.1 on 2025-06-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_booking_email_booking_referer_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
