# Generated by Django 5.2.1 on 2025-07-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalsettings',
            name='phone_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
