# Generated by Django 5.2.1 on 2025-06-06 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
    ]
