# Generated by Django 5.2.1 on 2025-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homeexplore_homerooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeRoomsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
