# Generated by Django 5.2.1 on 2025-06-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homeaboutimage_order_alter_homebanner_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeaboutimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='homeaboutimage',
            name='order',
        ),
    ]
