# Generated by Django 5.2.1 on 2025-06-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_hometeamsection_hometeamsectiontitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeTeamSectionTitle',
            new_name='HomeTeamTitleSection',
        ),
    ]
