# Generated by Django 5.2.1 on 2025-06-16 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_hometeamsectiontitle_hometeamtitlesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaboutimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='homeeatsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='homeexplore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='homegathersection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='homerooms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='hometeamsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='hometeamsection',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
