# Generated by Django 5.2.1 on 2025-06-16 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homeaboutimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometeamsection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='hometeamsection',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
