# Generated by Django 5.2.1 on 2025-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homeblogsection_homeblogtitlesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeblogsection',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
