# Generated by Django 5.2.1 on 2025-06-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homeroomstitle_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeroomstitle',
            name='link',
        ),
        migrations.AddField(
            model_name='homeabouttitle',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
