# Generated by Django 5.2.1 on 2025-06-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_homeroomstitle_link_homeabouttitle_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homerooms',
            name='link',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='homeroomstitle',
            name='link',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
