# Generated by Django 5.2.1 on 2025-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homerooms_link_homeroomstitle_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homerooms',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeroomstitle',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
